baseURL = "https://aditishenoy.github.io"
languageCode = "en-us"
title = "Aditi Shenoy"

theme = "hugo-casper-two-master"

disqusShortname = "https-aditishenoy-github-io"
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Aditi Shenoy"
  subtitle    = "I read. I write. I code."
  copyright   = "© 2019"

  cover       = "/img/sam.jpeg"
  description = ""
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  #RSSLink = "https://feedly.com/i/subscription/feed%2Fhttps%3A%2F%2Faditishenoy.github.io%2Findex.xml"

  linkedinName = "aditi-shenoy-287060bb"
  twitterName = "aditi_shenoy"
  githubName = "aditishenoy"
  #fbName = "aditi.shenoy.90"
  #mediumName = "aditishenoy"
  #tumblrName = "ms-quaintrelle"
  
  logo = ""
  orgName = "Aditi Shenoy"
  #orgWebsite = "https://www.telematika.org"
  #orgDescription = "Here is a description placeholder for your org"

  showSupport = false
  
  author = "Aditi Shenoy"
  authorAvatar = "/img/bit-aditi.jpg"
  authorLocation = "Bangalore, India"
  authorWebsite = "https://aditishenoy.github.io"
  #authorDescription = "Coder | Developer "

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 150

[[menu.main]]
  name = "Blog"
  url = "/tags/"
  weight = 100

#[[menu.main]]
#  name = "Thoughts"
#  url = "/categories/thoughts"
#  weight = 99

[[menu.main]]
  name = "Projects"
  url = "/projects"
  weight = 95

#[[menu.main]]
#  name = "List"
#  url = "/Quaintrelle's wish list"
#  weight = 80