baseURL = "https://aditishenoy.github.io"
languageCode = "en-us"
title = "Aditi Shenoy"

theme = "ezhil"
copyright   = "Aditi Shenoy © 2020"
#summaryLength = 20
#paginate        = 6

#SectionPagesMenu = "main"

[params]
  title       = "Aditi Shenoy"
  subtitle    = "PhD Candidate in Protein Bioinformatics and Machine Learning"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Research"
url = "/post"
weight = 3

[[menu.main]]
name = "Articles"
url = "/post"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/vividvilla/ezhil"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/aditi-shenoy-287060bb/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/aditi_shenoy"  

[taxonomies]
   tag = "tags"