baseURL = "https://aditishenoy.github.io"
languageCode = "en-us"
title = "Aditi Shenoy"

theme = "hugo-casper-two-master"

disqusShortname = "https-aditishenoy-github-io"
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Aditi Shenoy"
  subtitle    = "| Bioinformatics | Data Science | Digital Health |"
  copyright   = "© 2019"

  cover       = "/img/blog-cover.jpg"
  description = ""
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "aditi_shenoy"
  fbName = "aditi.shenoy.90"
  githubName = "aditishenoy"
  linkedinName = "aditi-shenoy-287060bb"
  
  logo = ""
  orgName = "Aditi Shenoy"
  #orgWebsite = "https://www.telematika.org"
  #orgDescription = "Here is a description placeholder for your org"

  showSupport = true
  
  author = "Aditi Shenoy"
  authorAvatar = "bit-aditi.jpg"
  authorLocation = "Bangalore, India"
  authorWebsite = "https://aditishenoy.github.io"
  #authorDescription = "Coder | Developer "

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 150

[[menu.main]]
  name = "Articles"
  url = "/categories"
  weight = 100

#[[menu.main]]
#  name = "Papers"
#  url = "/papers"
#  weight = 99

[[menu.main]]
  name = "Projects"
  url = "/projects"
  weight = 95

[[menu.main]]
  name = "The 30's List"
  url = "/The 30s list"
  weight = 80
